export const SHOW_LOADING = "SHOW_LOADING";
export const HIDE_LOADING = "HIDE_LOADING";
export const GET_ROLES = "GET_CURRENT_ROLES";
export const GET_PERMISSIONS = "GET_CURRENT_PERMISSIONS";
export const SET_CURRENT_PERMISSION = "SET_CURRENT_PERMISSION";
export const SET_CURRENT_ROLE = "SET_CURRENT_ROLE";
export const GET_ACTIONS = "GET_ACTIONS";
export const RESET_ALL_PERMISSION = "RESET_ALL_PERMISSION";
