export const WindowEvents = Object.freeze({
  TOAST_ERROR: "TOAST_ERROR",
  TOAST_SUCCESS: "TOAST_SUCCESS",
  INCREASE_LOADING: "INCREASE_LOADING",
  DECREASE_LOADING: "DECREASE_LOADING",
  CHANGE_LANGUAGE: "CHANGE_LANGUAGE",
});
