export const SHOW_LOADING = "SHOW_LOADING";
export const HIDE_LOADING = "HIDE_LOADING";
export const GET_CURRENT_ROLES = "GET_CURRENT_ROLES";
export const GET_CURRENT_PERMISSIONS = "GET_CURRENT_PERMISSIONS";
